apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-management-api
  template:
    metadata:
      labels:
        app: library-management-api
    spec:
      containers:
        - name: library-management-api
          image: <docker-hub-username>/library-management-api:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: library-management-api
spec:
  selector:
    app: library-management-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
